### ISSUE TITLE
License/modification

### ISSUE THREAD

**Issue by sbstnh** [abcminiuser/micromenu-v2#4]
I would like to use your menu in my projects in a modified form (e. g. for STM32, different naming schema and other changes), but am unsure in which way I'm allowed to modify and publish the modified version on github as a part of the software (obviously including a reference/link to the original work). Are there any restrictions?

Btw: Awesome little project!

**Comment by abcminiuser** [comment]
Hi!

This ancient project is "Royalty-free for all uses", i.e. released into the public domain. Feel free to use it for any purpose you wish on any platform you wish without payment or attribution.

**Comment by sbstnh** [comment]
Perfect, thank you for the clarification!
